name: color_theme
description: >-
  A color themeing solution with support for handling locally and
  globally applied themes, and the combination thereof.
version: 1.0.0
homepage: https://github.com/james-alex/color_theme

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_object_map: ^1.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
