name: color_theme
description: >-
  A color themeing solution with support for handling locally and
  globally applied themes, and the combination thereof.
version: 0.0.3
homepage: https://github.com/james-alex/color_theme

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_object_map: ^0.1.1

dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.2
